# Generated by Django 5.2 on 2025-04-28 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fituser',
            name='friend_requests_sent',
            field=models.ManyToManyField(blank=True, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
