# Generated by Django 5.2 on 2025-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workoutgroup_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fituser',
            name='generated_workout',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
