# Generated by Django 5.2 on 2025-04-28 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fituser_generated_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='group',
        ),
        migrations.AddField(
            model_name='challenge',
            name='competitors',
            field=models.ManyToManyField(blank=True, related_name='challenges_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
