# Generated by Django 5.2 on 2025-04-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=999)),
                ('repetitions', models.DecimalField(decimal_places=1, max_digits=999)),
                ('category', models.CharField(default='Strength Training', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fitnessdata',
            name='flights_climed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fitnessdata',
            name='steps',
            field=models.PositiveIntegerField(),
        ),
    ]
