# Generated by Django 5.2 on 2025-04-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_alter_fitnessdata_flights_climed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.TextField()),
                ('intensity', models.TextField()),
                ('reps', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AddField(
            model_name='fitnessdata',
            name='restingHR',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
    ]
