# Generated by Django 5.2 on 2025-04-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_delete_exercise_fitnessdata_restinghr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessdata',
            old_name='flights_climed',
            new_name='flights_climbed',
        ),
    ]
